name: Cleanup Workflow

on:
    workflow_run:
        workflows:
            - CI/CD Pioneer Pipeline Deploy Workflow
        types:
            - completed

jobs:
    cleanup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                run:
                    echo "AWS Credentials set"
                # can be uncommented after
            # - name: Destroy Infrastructure
            #   run: |
            #     ./infrastructure/destroy.sh

    
