name: CI/CD Pioneer Pipeline Deploy Workflow

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - develop
      
jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4

      - name: Install Make # Already present but might as well
        run: sudo apt-get install -y make

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/test" >> $GITHUB_ENV

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Project Requirements
        run: make requirements

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Run Bandit Checks (Security Linter)
        run: make run-bandit

      - name: Run Flake8 Checks (Code Linter)
        run: make run-flake8

      - name: Run Tests
        run: make run-test

      - name: Check Code Coverage
        run: make check-coverage

  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Make Deployment Script Executable
        run: |
          chmod +x ./infrastructure/deploy.sh

      - name: Deploy Infrastructure
        run: |
          ./infrastructure/deploy.sh